# Generated by Django 3.0.6 on 2020-06-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='media')),
                ('marks', models.IntegerField(default=0)),
                ('caption', models.TextField(max_length=500)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
    ]
